services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "postgres-tutorials"
    container_name: "postgres-demo"
    environment:
      POSTGRES_DB: "svc_backend_team"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres-demo"
    volumes:
        - db:/data/postgres-demo
    ports:
        - "5432:5432"
    restart: unless-stopped
volumes:
  db:
    external: true